#!/usr/bin/env python3
# Shani Chalisa (36239-36281), Shiva Panchamruta Snanam (8184-8219)

SHANI_CHALISA = {
    36239: "Doha: Victory to Ganesha, son of Parvati, giver of auspiciousness and compassion — remove the sorrows of the humble and bless them, O Lord.",
    36240: "Doha: Victory, victory to the great Lord Shani-deva — hear this prayer, O son of the sun; protect the honour of your devotees.",
    36241: "Chaupai: Victory, victory to compassionate Shani-deva, who ever protects and sustains his devotees.",
    36242: "He has four arms and a dark body; a jeweled crown gleams beautifully on his head.",
    36243: "His forehead is magnificent and pleasing; his brow is drawn in a terrifying crooked glance.",
    36244: "Earrings flash and shimmer at his ears; a pearl-and-gem garland glitters on his chest.",
    36245: "He holds a mace, trident, and axe in his hands; in an instant he destroys his enemies.",
    36246: "Pingala, Krishna, Chhaya's son, Yama, Konastha, Raudra — destroyer of sorrow.",
    36247: "Souri, Manda, Shani — these ten names; son of the sun, all worship him for their desires.",
    36248: "On whomever the Lord is pleased, he makes even a pauper a king in an instant.",
    36249: "He makes a mountain become straw at a glance, and straw become a mountain.",
    36250: "He gave Rama the royal forest, and turned Kaikeyi's mind against him.",
    36251: "In the forest he showed the illusory deer and deceived Mata Janaki's cleverness.",
    36252: "He struck Lakshmana with Shakti's lance and caused an uproar throughout the army.",
    36253: "He turned Ravana's judgment mad and increased his enmity with Ramachandra.",
    36254: "He reduced the golden Lanka to ruins; Hanuman's drum thundered.",
    36255: "You placed your foot on King Vikrama; the painted peacock swallowed the necklace.",
    36256: "The nine-lakh necklace got accused of theft; his hands and feet were cut off in punishment.",
    36257: "His great affliction showed its harshest face; he was made to turn the oil-press in a oil-presser's house.",
    36258: "Then he composed Vinaya, Raga, and Deepak; when the Lord was pleased he gave him happiness.",
    36259: "King Harishchandra's wife was sold; he himself drew water at a Chandala's house.",
    36260: "Similarly Nala's affliction too ended; a roasted fish leapt back into the water.",
    36261: "When Shani caught hold of Sri Shankar, he caused Parvati to become a sati.",
    36262: "With just one glance in his wrath, the head of Gauri's son flew into the sky.",
    36263: "When your affliction fell upon the Pandavas, Draupadi nearly became unclothed.",
    36264: "He crushed the Kauravas' mind and judgment too, and caused the great Mahabharata war.",
    36265: "He swallowed the sun in his mouth immediately and leapt down into the underworld.",
    36266: "The other gods then came and appealed; the sun was released from his mouth.",
    36267: "The Lord's vehicle has seven kinds — vulture, crow, donkey, deer, and dog.",
    36268: "Jackal, lion, and other clawed animals — with these the astrologers proclaim the fruits.",
    36269: "When the elephant-vehicle comes to a house, Lakshmi arrives; from the horse, happiness and wealth spring up.",
    36270: "The donkey causes great harm in many works; the donkey also accomplishes royal assemblies.",
    36271: "The jackal destroys one's intellect completely; the deer gives hardship and destroys life.",
    36272: "When the Lord comes riding a dog, fear of thieves and the like arises greatly.",
    36273: "Similarly the four padas have these names — gold, iron, silver, and copper.",
    36274: "When the Lord arrives in the iron pada, wealth and people's prosperity are destroyed.",
    36275: "The equal one and the copper and silver are auspicious; gold brings all happiness and good fortune.",
    36276: "Whoever sings this Shani-charitra daily will never be tormented by an inauspicious period.",
    36277: "The Lord shows wonderful sport and loosens the power of enemies.",
    36278: "Whoever invites a learned and worthy priest and properly appeases the planet Shani.",
    36279: "One who offers water to the peepal tree on Shani's day and gives lamp-donations attains great happiness.",
    36280: "Ramasundara, the Lord's servant, says: by remembering Shani, happiness shines forth.",
    36281: "Doha: One who recites this text of Shanishchara-deva for forty days crosses the ocean of worldly existence, becoming pure and ready.",
}

SHIVA_PANCHAMRUTA = {
    8184: "Ritual heading: Vamadevaya namah — the bath; this rite is performed at each occasion after removing the previous offerings.",
    8185: "Title and opening: the five-nectar bath (panchAmrita-snanam); salutation to the deities of the five nectars; offering of the sixteen-fold worship from meditation and invocation onward; Bhavani-Shankara.",
    8186: "Milk offering — Vedic mantra: 'May you swell, Soma; let your potency come from all sides; be the unifier of nourishment.' Salutation to Sri Bhavani-Shankara-svamin; bathing with milk.",
    8187: "Water mantra: 'O waters, you are the source of wellbeing; grant us vigour for the great sight; let us share in your most blissful essence, O eager ones, as mothers (share with their children).'",
    8188: "Curd offering — Vedic mantra: 'I have pleased Dadikravann, the swift victorious horse; may he make our mouths fragrant and extend our lives.' Salutation; bathing with curd.",
    8189: "Repeated water mantra: 'O waters, you are the source of wellbeing; grant us vigour for the great sight; let us share in your most blissful essence.'",
    8190: "Ghee offering — Vedic mantra: 'You are pure, you are light, you are radiance; may the god Savita purify you through the flawless sieve of the rays of the sun.' Bathing with ghee.",
    8191: "Repeated water mantra: 'O waters, you are the source of wellbeing; grant us vigour for the great sight; let us share in your most blissful essence.'",
    8192: "Honey offering — Vedic mantra: 'For righteousness the winds blow sweetness; the rivers pour sweetness; may the plants be sweet to us; sweet the night and sweet the dawn; sweet the earthly atmosphere.'",
    8193: "Repeated water mantra: 'O waters, you are the source of wellbeing; grant us vigour for the great sight; let us share in your most blissful essence.'",
    8194: "Sugar offering — Vedic mantra: 'Flow sweetly for the divine birth; sweetly for Indra of the good invocation; sweetly for Mitra, Varuna, and Vayu; sweetly for Brihaspati.'",
    8195: "Repeated water mantra: 'O waters, you are the source of wellbeing; grant us vigour for the great sight; let us share in your most blissful essence.'",
    8196: "Concluding declaration: 'Salutation to Sri Bhavani-Shankara-svamin; I offer the five-nectar bath.'",
    8197: "Conch-water bath — water mantra: 'O waters, you are the source of wellbeing; grant us vigour for the great sight; let us share in your most blissful essence.'",
    8198: "Fruit-water bath — Vedic mantra: 'Those plants that bear fruit, those that bear none, those that flower without fruiting — all sent forth by Brihaspati — may they release us from sin.'",
    8199: "Fragrant-water bath — Vedic mantra: 'The fragrance-gated, unconquerable, ever-nourishing, field-dwelling goddess, ruler of all beings — I invoke her here, Shri.'",
    8200: "Flower-water bath — Vedic mantra: 'Whoever knows the flower of the waters becomes flower-endowed, offspring-endowed, cattle-endowed; the moon is truly the flower of the waters.'",
    8201: "Unbroken-rice water bath — Vedic mantra: 'At your coming and going may the durva grass flower; may the ponds and the lotus-pools be like homes by the ocean.'",
    8202: "Gold-water bath — Vedic mantra: 'That became gold, that became the gold-metal; whoever knows the birth of gold (knows) thus.'",
    8203: "Rudraksha-water bath — Mahamrityunjaya mantra: 'We worship the three-eyed one, the fragrant one who nourishes all; may he release us from death as a cucumber from its stalk, not from immortality.'",
    8204: "Ash-water bath — Vedic mantra: 'Harm not the great nor the small among us, nor the growing one nor the grown; do not slay, O killer, the father nor the mother; harm not the beloved body.'",
    8205: "Bael-water bath — Vedic mantra: 'Harm not our offspring nor our life; harm not our cows nor our horses; slay not our heroes in your anger, O Rudra; here prostrate we call upon you.'",
    8206: "Durva-water bath — Vedic mantra: 'From joint to joint, from node to node you grow, O durva grass; so spread through us in thousands and hundreds.'",
    8207: "Sub-heading: the cleansing-impurity bath (malapakarshana-snanam) begins.",
    8208: "Vedic mantra (Hiranyavarna hymn): 'O golden-hued, pure, purifying waters in whom Kashyapa was born, in whom Indra — in whom Agni as embryo, the all-formed — may those waters protect us.'",
    8209: "Vedic mantra: 'Through whose middle King Varuna moves, observing the truth and untruth of men; the honey-dripping pure purifying waters — may those waters protect us.'",
    8210: "Vedic mantra: 'Those in which the gods make their drink in heaven, those that multiply everywhere in mid-space, those that water the earth with brilliance — may those waters protect us.'",
    8211: "Vedic mantra: 'O waters, look upon me with an auspicious eye; touch my skin with your auspicious body; may I invoke all fires settled in the waters — may splendour be in me.'",
    8212: "Atharva-Veda mantra (3.13): 'The rivers flow together, streaming down from the mountain — they speak of rivers, their names are Sindhu.'",
    8213: "Repeated water mantra: 'O waters, you are the source of wellbeing; grant us vigour for the great sight; let us share in your most blissful essence.'",
    8214: "Ritual instruction: 'Rest in the sky, abide in mid-space, arise from the earth; you are the Brahman-radiance; I seize the seizures of the waters, this is their power.'",
    8215: "Vedic mantra: 'The self-purifying one of excellent birth, the discerning one purified by the filter — may the one who is the purifier purify me; may the divine people purify me, may the Manus purify me by thought.'",
    8216: "Vedic mantra: 'By great Savita's purifiers, the highest divine thoughts — O Agni, purify me by discernment; by that by which the gods were purified, by which the divine waters purify.'",
    8217: "Vedic mantra: 'The purifying hymns are the path to wellbeing, richly milking, full of sap; the essence gathered by the seers, the immortal set among the Brahmins — may the purifying ones purify us.'",
    8218: "Vedic mantra: 'Waters are indeed all this; all beings are waters; breath is waters; animals are waters; food is waters; immortality is waters; the sovereign is waters; the viraat is waters.'",
    8219: "Vedic mantra: 'He leads forward the waters; one who has faith leads forward the waters; beginning with faith he leads forward and proceeds; he leads forward the waters — sacrifice indeed is waters; beginning with sacrifice.'",
}
