#!/usr/bin/env python3
# Brahma-samhita verses 39-63 (ids 22422-22446)
BS_REMAINING = {
    22422: "Govinda, the primeval Lord, abides in Rama and other forms according to rule, yet Krishna himself became the Supreme Person.",
    22423: "I worship Govinda, the primeval Lord, whose effulgence is the undivided Brahman containing the limitless universes with all their varied splendours.",
    22424: "I worship Govinda, the primeval Lord, whose Maya, spreading the threefold qualities as the subject of the Vedas, gives birth to hundreds of universes, while he himself rests on pure transcendent sattva.",
    22425: "I worship Govinda, the primeval Lord, who as the essence of blissful spiritual consciousness reflects himself in the minds of all beings and by his playful sport effortlessly conquers the worlds.",
    22426: "I worship Govinda, the primeval Lord, in whose Goloka dhama and below in the abodes of Devi, Mahesh, and Hari, the respective divine glories are all established by him.",
    22427: "I worship Govinda, the primeval Lord, whose shadow is Durga, the single power of creation, sustenance, and dissolution bearing the worlds, acting only according to his will.",
    22428: "I worship Govinda, the primeval Lord, from whom Shambhu comes as his derivative for a purpose, as curd arises from milk by transformation yet is not separate from its cause.",
    22429: "I worship Govinda, the primeval Lord, from whom Vishnu shines forth as a lamp lit from a lamp, bearing the same qualities with the same revealed cause.",
    22430: "I worship Govinda, the primeval Lord, whose own supreme form is Mahavisnu lying in yogic sleep in the waters of the Causal Ocean, his body-pores containing infinite universes, resting on the support-power.",
    22431: "I worship Govinda, the primeval Lord; Maha-Vishnu is but a special part of his plenary portion, within whose single breath the lords of countless universes live out their span.",
    22432: "I worship Govinda, the primeval Lord; Brahma who fashions the universal egg is like the sun revealing in fragments of stone only a portion of his own light.",
    22433: "I worship Govinda, the primeval Lord; Ganesha, lord of the ganas, places Govinda's tender lotus-feet on the twin pot-shaped protuberances of his crown at the time of prostration, thereby capable of removing all obstacles of the three worlds.",
    22434: "I worship Govinda, the primeval Lord, from whom arise fire, earth, sky, water, wind, the directions, time, the individual self, and mind — from whom the three worlds come forth, subsist, and re-enter.",
    22435: "I worship Govinda, the primeval Lord; the sun, eye of all planets, embodiment of all divine forms, full of limitless radiance, revolves in his appointed time-cycle only by Govinda's command.",
    22436: "I worship Govinda, the primeval Lord; all dharma and sin, the Vedas, austerities, and all living beings from Brahma down to insects and birds — their very capacity to manifest proceeds only from the gift of his glory.",
    22437: "I worship Govinda, the primeval Lord, who allots the fruits of karma to every being from the small red insect to Indra himself according to their acts, yet burns up the karma of his devotees entirely.",
    22438: "I worship Govinda, the primeval Lord; those who contemplate him with anger, lust, natural affection, fear, love, bewilderment, reverence, or devotion all attain a form like his.",
    22439: "I worship Govinda, the primeval Lord, whose Goloka abode is filled with Shri-consorts and wish-granting trees, whose ground is made of cintamani gems, whose waters are nectar, whose speech is song, whose every movement is dance, and where the flute plays as dearest friend.",
    22440: "Then Maha-Vishnu, the Blessed One, addressed Brahma the progenitor: 'O Brahma, if your mind is set on knowing greatness and on the work of creation, receive from me this five-verse wisdom, dear child.'",
    22441: "When the Self is purified by knowledge and devotion, the highest bhakti characterised by love of the Lord arises in it, shining with the bliss of pure consciousness.",
    22442: "By sound reasoning, by virtuous conduct, by constant practice — illumining oneself by the Self — one attains that highest bhakti.",
    22443: "There is nothing superior to bhakti; through it one attains Govinda himself.",
    22444: "Abandoning all dharmas take refuge in me alone; faith determines the fruit — I am the seed of all moving and unmoving things.",
    22445: "Bear my power, O Brahma; I am the seed of all moving and unmoving things; there is no cause higher than I.",
    22446: "Colophon: Thus ends the auspicious Brahma-Samhita.",
}
