#!/usr/bin/env python3
# Chanakya Neethi ch12 (14915-14937), ch16 (14996-15015)
# Prashnopanishad Q1 (39114-39131), BG Dhyana Slokas (30456-30470)

CHANAKYA_12 = {
    14915: "A home full of joy, wise children, a wife of pleasant speech, satisfaction of desires from one's own wealth, pleasure in one's own wife, obedient servants, hospitality, worship of Shiva, a learned and generous king — who that has these six needs heaven?",
    14916: "One who gives even a small gift to a Brahmin in affliction with compassionate faith obtains boundless merit, O king — what is given to Brahmins can never be recovered.",
    14917: "Kindness to one's own kin, compassion to strangers, cunning to the wicked, affection to the virtuous, smile to the base, straightforwardness to the learned, bravery against enemies, patience with the guru — the wise man who knows the right measure for each is the true wise man.",
    14918: "Hands that have not given in charity, ears that are enemies of sacred learning, eyes that have never seen the good, feet that have not gone to holy places, a belly filled with wealth unjustly earned, a head that has never bowed to the Lord — of what use is the body bearing all these?",
    14919: "Those men in whom there is no devotion to the lotus-feet of the son of the glorious Yashoda, whose tongues are not attached to recounting the beloved qualities of the cowherd's daughter's dear one, whose ears drink not the nectar of Krishna's sport — for them living is useless.",
    14920: "When the karil-bush has no leaf, is it the spring's fault? If the owl cannot see by day, is that the sun's defect? When rain does not fall in a chataka bird's mouth, is the cloud to blame? When destiny is unfavourable, who is responsible?",
    14921: "The company of the good makes the wicked virtuous, while the wicked do not make the good wicked — the earth holds the fragrance of flowers, not the flowers the earth's smell.",
    14922: "The sight of the virtuous is itself meritorious, for the virtuous are themselves sacred fords; a pilgrimage bears fruit in time, but the company of the good bears fruit instantly.",
    14923: "O Brahmin, who is great in this city? Tell me — the palmyra trees are the crowd; who is a giver? The washerman who takes clothes in the morning and gives them back at night; who is clever? One who takes another's wealth and wife — everything is relative.",
    14924: "Houses devoid of the washing of Brahmin feet, devoid of the sound of Vedic scripture and sacrificial chanting, devoid of the 'svaha' and 'svadha' offerings — they are equal to a cremation ground.",
    14925: "Truth is mother, knowledge is father, righteousness is brother, compassion is friend, peace is wife, forgiveness is son — these six are my kinsmen.",
    14926: "Bodies are impermanent, wealth is not eternal, death is ever nearby — one should always accumulate dharma.",
    14927: "Brahmins rejoice in being invited; cows rejoice in fresh grass; a wife rejoices when her husband is eager; I rejoice in the feet of Krishna.",
    14928: "One who looks upon another's wife as a mother, another's wealth as a clod of earth, and all beings as oneself — that one is a pandit.",
    14929: "Engagement with dharma, sweetness in speech, eagerness in giving, straightforwardness with friends, humility with the guru, deep stability in the heart, purity in conduct, relish for virtue, erudition in scripture — whoever has these is truly a man.",
    14930: "The wish-granting tree is wood; Sumeru moves; the cintamani is a stone; the sun's rays are sharp; the moon wanes; the ocean is salt water; Kama lost his body; Indra was struck down — when fate is against them, even the great are reduced.",
    14931: "Knowledge is a friend in travel; a wife is a friend at home; medicine is a friend to the sick; dharma is a friend to the dead.",
    14932: "Learn humility from princes, eloquence from the learned, falsehood from gamblers, and cunning from women.",
    14933: "One who spends without thinking, who has no patron, who loves quarrel, who is sick everywhere — such a person quickly perishes.",
    14934: "The wise should not worry about food, but think only of dharma — for man's food is born together with him at birth.",
    14935: "One who has shed shame in earning wealth, in gathering knowledge, in eating, and in worldly dealings — that one lives happily.",
    14936: "As a pot is filled drop by drop, so gradually are all learning, dharma, and wealth accumulated.",
    14937: "A wicked person remains wicked even in old age, just as the bitter colocynth does not become sweet even when fully ripe.",
}

CHANAKYA_16 = {
    14996: "The Lord's feet were not properly meditated upon to cut the bonds of worldly life; dharma, capable of opening heaven's gates, was not earned; the woman with full breasts and broad thighs was not even enjoyed in a dream — life was spent in vain.",
    14997: "Women speak sweet words with one, look with longing at another, and think of yet another in their hearts — a woman's affection is never fixed on one alone.",
    14998: "The fool who in delusion thinks 'this beloved woman is devoted to me' becomes her slave and dances like a caged bird.",
    14999: "Who having gained wealth is not proud? Whose calamity has not set? Whose mind has not been cut to pieces by women? Who is dear to a king forever? Who is not swallowed by death? Who prospers by association with the wicked?",
    15000: "A golden deer was neither created, nor ever seen before, nor ever heard of — yet Rama's desire for it arose; at the time of destruction the intellect turns contrary.",
    15001: "One rises to excellence through qualities, not by occupying a high seat — does the crow seated on the pinnacle of a palace become a Garuda?",
    15002: "Qualities are honoured everywhere, not great riches — is the full moon as worthy of veneration as the thin but spotless crescent?",
    15003: "Even one without qualities becomes virtuous when his qualities are praised by others; even Indra diminishes when he himself proclaims his own virtues.",
    15004: "Qualities reach their charm when they come to one of discernment — a gem shines far more beautifully when set in gold.",
    15005: "Even one equal to the all-knowing through his qualities fades when he stands alone without support — even a priceless ruby needs gold as its base.",
    15006: "Wealth obtained with excessive pain, happiness gained through excessive greed, and service to an enemy — may none of these ever be mine.",
    15007: "What use is a wealth that sits confined like a bride kept indoors? But wealth that like a courtesan is enjoyed freely by all passers-by — that is worthy.",
    15008: "In matters of wealth, of survival, of women, of food and activity — all living beings have been unsatisfied, are unsatisfied, and will be unsatisfied.",
    15009: "All gifts, sacrifices, fire-offerings, and oblations diminish over time; but the gift of safety to all beings, and the gift to a worthy vessel — these never diminish.",
    15010: "Grass is light, lighter still is cotton, lighter than that is the beggar — why has the wind not carried him away? Because it fears he will beg from it.",
    15011: "Better is death with honour than life with dishonour — death brings pain for a moment, dishonour brings pain day after day.",
    15012: "All living creatures are pleased by giving kind words; therefore kind words should always be spoken — what poverty is there in speech?",
    15013: "There are two fruits on the bitter tree of worldly existence that are like nectar — noble speech sweetly tasted, and the company of the good.",
    15014: "What was practised birth after birth — giving, study, austerity — by the very force of that practice the embodied soul practises it again.",
    15015: "Knowledge that stays only in a book, wealth in another's hand — at the moment of need neither is knowledge nor is wealth.",
}

PRASHNOPANISHAD = {
    39114: "Chapter heading: The First Question.",
    39115: "Opening invocation: Om, salutation to the Supreme Self; Hari Om.",
    39116: "Sukesha of the Bharadvaja clan, Saibya Satyakama, Gargya of the Sauryayani lineage, Kausalya of the Ashvalayana lineage, Bhargava of the Vaidarbhi lineage, and Kabandhi of the Katyayana lineage — all devoted to Brahman, established in Brahman, seeking the highest Brahman, came to the sage Pippalada with fuel in hand.",
    39117: "The sage said to them: 'Live with me for a year with austerity, celibacy, and faith; then ask whatever you wish — if I know, I will tell you everything.'",
    39118: "Then Kabandhi Katyayana approached and asked: 'Venerable sir, from what are all these creatures born?'",
    39119: "To him the sage replied: 'Prajapati, the Lord of beings, desired offspring; he performed austerity, and having performed austerity he produced a pair — Rayi (matter) and Prana (life), thinking these two will produce creatures for me in many ways.'",
    39120: "The sun is indeed Prana; the moon is indeed Rayi — Rayi is all this, whatever is formed and whatever is formless; therefore form itself is Rayi.",
    39121: "The sun, rising, enters the eastern direction and thereby holds the eastern living beings in his rays; entering the south, the west, the north, the zenith, the nadir, and the intermediate quarters, he holds all living beings.",
    39122: "That same Vaisvanara of universal form — Prana as fire — rises; this has been declared by the verse.",
    39123: "The sun who is of universal form, tawny, all-knowing, the ultimate resort, the single blazing light, bearing a thousand rays, revolving in a hundred ways — he rises as the Prana of all beings.",
    39124: "The year itself is Prajapati; his two paths are the southern and the northern: those who perform only sacrifices and public works relying on those paths gain the lunar world and return.",
    39125: "But those who by austerity, celibacy, faith, and knowledge seek the Self win the solar world — that is the ultimate abode of all life-breaths, the immortal, the fearless; from that they do not return.",
    39126: "They say: the five-footed, twelve-formed Father abides in the farther half of the sky as the full one; others say he is set in the seven-wheeled six-spoked chariot.",
    39127: "The month indeed is Prajapati; its dark fortnight is Rayi, its bright fortnight is Prana — therefore these seers perform their rites in the bright fortnight.",
    39128: "Day and night indeed are Prajapati; the day itself is Prana, the night itself is Rayi — those who unite in pleasure by day waste their Prana; celibacy alone is that.",
    39129: "Food itself is Prajapati; from food comes seed; from that all these creatures are born.",
    39130: "Those who follow the Prajapati-vow produce offspring; theirs is the Brahma-world in which austerity, celibacy, and truth are established.",
    39131: "For them that Brahma-world is pure in which there is no crookedness, no falsehood, no illusion.",
}

BG_DHYANA = {
    30456: "Om — this Bhagavad Gita, revealed by Bhagavan Narayana himself to Partha, woven by the ancient sage Vyasa into the Mahabharata, this goddess pouring the immortal rain of non-duality, eighteen chapters long — may I meditate on it.",
    30457: "Salutation to you, O Vyasa of vast intellect, with eyes wide as a full-blown lotus — you who lit the lamp full of the oil of the Bharata and made it shine with the light of knowledge.",
    30458: "Salutation to Krishna — the wish-fulfilling tree of those who have surrendered, who holds the goad and whip in one hand, who displays the gesture of knowledge, and who is the milch-cow of the Gita's nectar.",
    30459: "I bow to Krishna, son of Vasudeva, slayer of Kamsa and Chanura, the supreme joy of Devaki, teacher of the world.",
    30460: "The Mahabharata battlefield is a river whose banks are Bhishma and Drona, whose waters are Jayadratha, whose blue lotus is Gandhara's king, whose crocodile is Shalya, whose current is Kripa, whose billow is Karna — Arjuna crossed it on the boat of Krishna.",
    30461: "This spotless lotus of the Gita — born of the Mahabharata lake, spreading the fragrance of the Gita's meaning, with petals of many narratives, awakened by the call of Hari-katha — let it be eagerly drunk every day by the good bees of the world.",
    30462: "He who makes the mute speak and the lame cross mountains — at whose grace I bow: the blissful Madhava.",
    30463: "I bow to Vishnu of peaceful bearing, resting on the serpent, lotus-naveled, lord of the gods, support of the universe, sky-like, cloud-hued, of auspicious limbs, beloved of Lakshmi, lotus-eyed, meditated upon in the hearts of yogis.",
    30464: "Him whom Brahma, Varuna, Indra, Rudra, and the Maruts praise with divine hymns, whom the Sama-singers sing with the Vedas, angas, pada, krama, and Upanishads, whom the yogis see in meditation — that immovable one, I salute.",
    30465: "Having bowed to Narayana and to Nara the highest of men, to goddess Sarasvati and to Vyasa — then let one utter victory.",
    30466: "Salutation to Krishna who is of the nature of Sat-Chit-Ananda, the effortless doer, knowable through Vedanta, the Guru, the witness of the intellect.",
    30467: "All the Upanishads are cows, the milker is the cowherd's son, Partha is the calf, the wise drinker, and the great nectar of the Gita is the milk.",
    30468: "Phalashruti: whoever reads this holy Gita-shastra with concentration attains Vishnu's abode, free from fear and grief.",
    30469: "One scripture — the Gita sung by the son of Devaki; one God — the son of Devaki alone; one mantra — his various names; one action — service to that God alone.",
    30470: "Om Sri Krishnaya Paramatmane Namah — salutation to Krishna the Supreme Self.",
}
