#!/usr/bin/env python3
# kyts-jata (34958-35010) and kyts-1.8 (17263-17312)

KYTS_JATA = {
    34958: "Vedic jata-patha recitation unit: the mantra 'prajananam jyotih' (light of procreation) repeated in interleaved forward-backward pattern.",
    34959: "Jata-patha unit: 'kamam kamayate' (he who desires, desires) — syllable-reversal recitation drill.",
    34960: "Jata-patha unit: 'nyamardam' — syllable-interlocked recitation with Vedic accent marks.",
    34961: "Jata-patha unit: 'Prajapati' (Lord of creatures) — interlocked recitation establishing the name.",
    34962: "Jata-patha unit: 'saman rajanya' — the Kshatriya class linked to Vedic chanting in interlocked recitation.",
    34963: "Jata-patha unit: 'asrjyata vairajam' (Vairaja was emitted) — recitation of creation text.",
    34964: "Jata-patha unit: 'pratasavane' (at the morning pressing) — Soma-ritual term in jata recitation.",
    34965: "Jata-patha unit: 'brahmavadinah vadanti' (the Brahma-speakers declare) — theological statement in interlocked pattern.",
    34966: "Jata-patha unit: 'prajam tasya' (his offspring) — recitation of progeny passage.",
    34967: "Jata-patha unit: 'yajnena yajamanah' (the sacrificer by sacrifice) — jata drill on ritual efficacy.",
    34968: "Jata-patha unit: 'angiras satram' (Angiras's sacrificial session) — ancient Vedic rite in jata pattern.",
    34969: "Jata-patha unit: 'abhiplavah purvam' (the abhiplava rite first) — Vedic soma-festival term.",
    34970: "Jata-patha unit: 'ahar tat saman bhavati' (that day becomes the Saman) — correlation of day and chant.",
    34971: "Jata-patha unit: 'apah vai idam' (waters are indeed this all) — cosmological mantra in jata recitation.",
    34972: "Jata-patha unit: 'yatha aham yushmaan' (as I to you) — mutuality formula in interlocked pattern.",
    34973: "Jata-patha unit: 'shatani trayastrimshat' (three-hundred thirty-three) — numerical count in Vedic recitation.",
    34974: "Jata-patha unit: 'vyavairyata tasmat' (from that it separated) — cosmogonic separation passage.",
    34975: "Jata-patha unit: 'esham lokhanam' (of these worlds) — world-enumeration in jata recitation.",
    34976: "Jata-patha unit: 'evam shamsati' (thus he proclaims) — recitation of proclamation formula.",
    34977: "Jata-patha unit: 'dvibhagam brahmanae' (two parts to the Brahmin) — ritual share formula.",
    34978: "Jata-patha unit: 'somo vai sahasram' (Soma found the thousand) — Soma mythology in jata.",
    34979: "Jata-patha unit: 'pari pashyamah amsham' (we see all around the share) — soma-purchasing formula.",
    34980: "Jata-patha unit: 'shaatais somah kritah' (Soma purchased with hundreds) — purchase rite recitation.",
    34981: "Jata-patha unit: 'bhavati tam apsu' (it becomes, into waters) — waters-ritual passage.",
    34982: "Jata-patha unit: 'varo deyah sa hi' (that gift, for she indeed) — gift formula in recitation.",
    34983: "Jata-patha unit: 'kalyanee rupasamrddha' (the auspicious, abundantly beautiful) — epithet formula.",
    34984: "Jata-patha unit: 'ardhayati prajavaan' (the progeny-blessed halves) — ritual progeny passage.",
    34985: "Jata-patha unit: 'karoti rupani juhoti' (it makes forms and offers) — oblation formula.",
    34986: "Jata-patha unit: 'sahasratamya' (the thousandth) — ordinal number in Vedic recitation.",
    34987: "Jata-patha unit: 'ma pratistham gamaya' (lead me to a firm footing) — prayer for establishment.",
    34988: "Jata-patha unit: 'pratigrhnaati tam' (he receives her) — ritual reception formula.",
    34989: "Jata-patha unit: 'ityaha syona' (thus he says, auspicious) — concluding formula.",
    34990: "Jata-patha unit: 'atri radadat' (Atri gave) — Atri-sage gift narrative in jata.",
    34991: "Jata-patha unit: 'ye udyantah stomah' (the rising praises) — Vedic stotra-offering formula.",
    34992: "Jata-patha unit: 'Jamadagni pushtikamah' (Jamadagni desirous of nourishment) — sage-desire passage.",
    34993: "Jata-patha unit: 'samvatsaro vai' (the year indeed) — year as Prajapati in jata recitation.",
    34994: "Jata-patha unit: 'ya evam vidvan' (one who knows thus) — knowledge formula in jata.",
    34995: "Jata-patha unit: 'aharat tena yajata' (he took it thereby he sacrificed) — sacrificial action.",
    34996: "Jata-patha unit: 'rtusv eva samvatsare' (in the seasons, in the year) — time-cycle correlation.",
    34997: "Jata-patha unit: 'devasya tva savituh' (O Savita divine) — sun-deity invocation in jata.",
    34998: "Jata-patha unit: 'vibhur matraa prabhuh' (the all-pervading lord, by the measure) — divine measure formula.",
    34999: "Jata-patha unit: 'ayanaya svaha' (svaha to the journey) — oblation formula for the ritual path.",
    35000: "Jata-patha unit: 'agnaye svaha somaya svaha' (svaha to Agni, svaha to Soma) — fire and moon oblations.",
    35001: "Jata-patha unit: 'prthivyai svaha antarikshaya svaha' (svaha to earth, svaha to mid-space) — three-world oblations.",
    35002: "Jata-patha unit: 'agnaye svaha somaya svaha' — repeated fire-Soma oblation formula in jata recitation.",
    35003: "Jata-patha unit: 'prthivyai svaha antarikshaya svaha' — repeated earth and mid-space oblation.",
    35004: "Jata-patha unit: 'bhuvah devanam karmanam' (of the gods of the earth and actions) — cosmic correspondence formula.",
    35005: "Jata-patha unit: 'sharada tva rtuna hrtu' (by autumn, by the season) — seasonal ritual formula.",
    35006: "Jata-patha unit: 'inkaranaya svaha' (svaha to the sacred syllable 'in') — seed-syllable oblation.",
    35007: "Jata-patha unit: 'asisyate svaha' (svaha to one who shall rest) — prospective rest formula.",
    35008: "Jata-patha unit: 'vikshyamananaya svaha' (svaha to the observing one) — witnessing-consciousness formula.",
    35009: "Jata-patha unit: 'agnaye svaha vayave svaha' (svaha to Agni, svaha to Vayu) — fire and wind oblations.",
    35010: "Colophon: End of section 20 of the jata-patha recitation manual.",
}

KYTS_18 = {
    17263: "Title inscription: Krishna Yajurveda Taittiriya Samhita, First Kanda, Eighth Prashna — the Rajasuya (royal consecration).",
    17264: "Opening invocation: salutation to the Supreme Self, to Mahagana-pati, and to the Guru; Hare Om.",
    17265: "Ritual instruction: one offers to Anumaati (the deity of consent) a purodasha cake on eight potsherds; cows are the fee for those on the south side of the forked stake.",
    17266: "Ritual instruction: an eleven-potsherd cake to Indra with gold as fee; a bull as the fee; an eight-potsherd cake to Agni; an eleven-potsherd cake to Indra.",
    17267: "Ritual instruction: an eight-potsherd cake to Agni, a gruel to Soma, a twelve-potsherd cake to Savita, a gruel to Sarasvati, and gruel to Pushan.",
    17268: "Ritual instruction: an eleven-potsherd cake to Indra-Agni, curds of Maruta, curds of Varuna, and a one-potsherd cake to Kaya — the oblations for the seasonal rite.",
    17269: "Ritual instruction: an eight-potsherd cake to Agni Anikavat is offered, rising together with the sun; to the Maruts Santapana.",
    17270: "Ritual instruction: seven-potsherd cake to the playful Maruts, offered rising together with the sun — I carry it down for you.",
    17271: "Ritual instruction: a six-potsherd cake to Soma with the ancestors; to the pitrs of the Barhishad class — scattered grain as offering.",
    17272: "Vedic mantra: 'They ate, they rejoiced, they honour the beloved ones; the inspired ones praised with the newest thought — yoke now Indra.'",
    17273: "Vedic mantra: 'May our mind return again to wisdom and strength for living; and may we see the sun long; may the fathers restore our mind, O Punarvasu.'",
    17274: "Ritual instruction: one potsherd is offered per person, one extra beyond those of the household; what was not done for animals — the rite proceeds.",
    17275: "Ritual text: 'Auspicious for the sheep, for the ewe — away from Rudra; as our prosperity, free from harm.'",
    17276: "Ritual instruction: a twelve-potsherd cake for Indra-Agni, gruel for the Vishvedevas, a twelve-potsherd cake for Indra-Shunasira, and for Vayu.",
    17277: "Mantra: 'Homage to you, svaha! — the gathered raksha (demon-force) is consumed; I burn this raksha down with fire.'",
    17278: "Ritual instruction: twelve-potsherd cake to Dhata, gruel to Anumaati, gruel to Raka, gruel to Sinivali.",
    17279: "Ritual instruction: gruel to Brihaspati, offered in the Brahmin's house with a white-backed animal as fee; an eleven-potsherd cake for the Rajanya.",
    17280: "Ritual instruction: in the charioteer's house an impure animal as fee; an Ashvin's two-potsherd cake in the collector's house — two saved.",
    17281: "Ritual instruction: in the square vessel, picked separately for the self-growing branch, ear by ear and kernel by kernel — those who remain on one side.",
    17282: "Ritual instruction: eight-potsherd cake to Agni Griha-pati from black rice; to Soma Vana-pati.",
    17283: "Vedic mantra: 'Brihaspati is lord of speech, Indra of the mighty, Mitra of the truthful, Varuna of the righteous — ye gods.'",
    17284: "Vedic mantra: 'You are the station, you are the lord of waters, you are the bull, you are Ursasena, you are the pasture-protector, you are the strength of the Maruts.'",
    17285: "Vedic mantra: 'O divine waters, sweet ones, come forth with sweetness — great brilliance for the Kshatriya, unconquerable, drawing to yourself.'",
    17286: "Vedic mantra: 'You are the womb of dominion, most motherly; Agni Griha-pati found out, the fire found out.'",
    17287: "Vedic mantra: 'You are Indra's thunderbolt, the Vrtra-slayer — by you conquer that Vrtra and the enemy-banishing powers; protect me against the opponent.'",
    17288: "Ritual instruction: stand on the fuel-stick; the Gayatri meter protect you; trivrit stotra; the Rathantara Saman; Agni is the deity; Brahma is the overseer.",
    17289: "Ritual instruction: the ekavimshat stotra; the Vairaja Saman; Mitra-Varuna as deities; strength and wealth — stand upward.",
    17290: "Ritual formula: 'svaha to Agni, svaha to Soma, svaha to Savita, svaha to Sarasvati, svaha to Pusha.'",
    17291: "Vedic mantra: 'You are Soma's brilliance — may his brilliance be mine; you are immortality, protect me from death; let the light protect me from falling away.'",
    17292: "Ritual formula: 'With the lustre of fire, the radiance of the sun, the power of Indra, the heroism of Mitra-Varuna, the force of the Maruts, the dominion.'",
    17293: "Vedic mantra: 'You are Indra's thunderbolt, the Vrtra-slayer — by you conquer that Vrtra; the powers of Mitra and Varuna rule you.'",
    17294: "Vedic mantra: 'May mother Earth not harm me in my life-span; give me life, give me vigour; yoke my strength.'",
    17295: "Vedic mantra: 'You are Mitra, you are Varuna; together with all the gods; you are the navel of dominion, the womb of dominion, auspicious.'",
    17296: "Ritual formula: 'O king, the Brahmin is with you, you are Mitra, auspicious — O king the Brahmin is with you.'",
    17297: "Ritual instruction: an eight-potsherd Agneya cake with gold as fee; gruel to Sarasvati; a heifer as fee; Saavitra twelve-potsherd cake.",
    17298: "Ritual instruction: consecration on the same day, Soma purchased on the same day; he gives a garland of water-lilies; ten heifers for Soma.",
    17299: "Ritual instruction: eight-potsherd Agneya cake; gold as fee; eleven-potsherd cake to Indra; a bull as fee; gruel for the Vishvedevas.",
    17300: "Ritual instruction: eight-potsherd Agneya cake; gruel to Soma; twelve-potsherd Savitra cake; gruel to Brihaspati.",
    17301: "Vedic mantra: 'Sweet one with the sweet, strong one with the strong, immortal one with the immortal I release; with Soma I send forth Soma.'",
    17302: "Vedic mantra: 'O Agni-Vishnu, great indeed is that greatness of yours; you hold the hidden names of ghee; in each home you bear seven treasures.'",
    17303: "Vedic mantra: 'Let Sarasvati the sacrificial one come to the sacrifice; may the goddess delight and come, filled with ghee, speaking sweet speech to us.'",
    17304: "Vedic mantra: 'Born at the right season, place wealth and splendour in us; O Mitra-Varuna, sprinkle the pasture with ghee; honey-sweet.'",
    17305: "Vedic mantra: 'The hero in battles whosoever — the mind of gods which the sacrificer wishes to please reaches beyond him who does not sacrifice.'",
    17306: "Vedic mantra: 'Streams of ghee come from all sides eager for glory; O Soma-Rudra, loosen the disease that oppresses our home.'",
    17307: "Ritual summary: list of oblation deities — Anumaati, Agneya, Aindragni, Agni-Soma, for each person, Aindragni, Dhata, Barhaspati.",
    17308: "Ritual summary: list of verses — Anumaati, 'yatha asati,' the divine waters, Mitra, the hero, forty-two.",
    17309: "Ritual summary title: Anumaati and the cows — (ritual section heading).",
    17310: "Ritual summary: Isha, the waters, Devasya, I take, gods-and-demons, be well, the domestic sacrifice, Anumaati, eight (ritual items enumerated).",
    17311: "Closing mantra: Hari Om.",
    17312: "Colophon: The eighth prashna of the first kanda of the Krishna Yajurveda Taittiriya Samhita is complete.",
}
