#!/usr/bin/env python3
# Amba-stavam (32000-32032), Devi-aparajita (30405-30432)

AMBA_STAVAM = {
    32000: "Taking refuge solely in her, I seek the shelter of that Goddess whom the sages call the primeval Nature, whom the knowers of Vedic secrets call Vidya, who bears the half-blossomed gesture of Shankara's form.",
    32001: "O Mother, in praising you even the weavings of speech become blunt; yet this child's praise, however improper, will reach you whose heart is melted by maternal love.",
    32002: "As sky, as the bindu, as the nada, as the crescent moon, as form, as the body of vag-bhava, as the matrix of letters — you shine in the mind of the fortunate as the outflowing nectar of blissful consciousness.",
    32003: "Those who worship your feet in the worlds with bodies covered in goosebumps, eyes ever streaming tears, and speech stumbling in broken words — O Mother, they are the truly blessed.",
    32004: "Whatever face rises to praise you, whatever head bows in salutation, whatever heart has you as its refuge — O Devi, by whom and with what do those belong?",
    32005: "O Bhavani, you arise from the hollow of the root-lotus, pierce the six lotus-centres like a lightning-creeper, and re-enter at the lunar orb of the polar region pouring down the supreme ambrosia.",
    32006: "When Manmatha had been burned to a single ash, your soft sidelong glance made him bud again in countless forms — and so, O Devi, the frontal eye has since then kept itself modestly folded, as if ashamed.",
    32007: "O daughter of the mountain-king, who knew beforehand that you, the supreme, would first take the hand of Shambhu — that wandering beggar, skull-bearing, naked, matchless — at an auspicious marriage?",
    32008: "A skin for garment, ash of a corpse for ointment, wandering for alms, dancing in a cremation ground, keeping company with ghosts and spirits — all this unseemliness of Shambhu shines as beauty because of your companionship, O Girijaa.",
    32009: "His fierce, sharp dances at the dissolution of the aeons — even those, O Mother, become gentle at your glance and transform themselves into the graceful lâsya, the world's delight.",
    32010: "O Kalyaani, when in his last body a creature has equal karma and the teacher's glance falls in compassion, the entire web of fetters is severed in an instant and the Shaambhava initiation is bestowed.",
    32011: "You flash in the mind adorned with pearl ornaments, red as fresh coral — like a starlit twilight; that one man alone becomes Manmatha for all three-world beauties.",
    32012: "Those who meditate upon you, O queen of immortals, nourishing the worlds with the current of nectar from your rays — they truly cross what even Brahma and the chief gods cannot cross.",
    32013: "One who meditates upon you, O Mother, as the white-as-autumn-moon one seated on a lotus, holding crystal rosary, book, and water-pot, hand raised in explanation — he becomes the vessel of all knowledge.",
    32014: "I bow to you alone as the Shabari — wearing a peacock-feather diadem, with tangled glossy hair, jewelled with gunja-berry necklaces on your full dark breasts, dark-complexioned, with coral lips, delicate hands, wife of the hunter.",
    32015: "O naive one, was only the tender new creeper half purchased, while this rough half was bought cheaply by the Lord? — I think the teasing words of your companions were silenced by the soft smile of that expression, O Devi.",
    32016: "This ocean of Maya, brimming with universes like bubbles and waving with various waves of suffering — O Mother, how it is instantly destroyed by the great submarine fire of unbroken meditation on you.",
    32017: "As Dakshayani, as the Crooked One, as the Cave-dweller, as Katyayani, as Kamala, as the Adept — though one and true, O Blessed Lady, you appear in many forms like a dancer.",
    32018: "In the place called the Anahata, defined by joy, your form transformed as nada is known by the inward-facing mind — the fortunate proclaim it with tears and goosebumps.",
    32019: "You are the moonlight in the moon and radiance in the fierce sun; you are consciousness in the person and strength in the wind; you are sweetness in water, heat in fire — nothing is without you.",
    32020: "Whatever lights move in the sky, whatever is in mid-space, whatever milk the she-serpent draws from the earth, whatever wind blows, whatever fire blazes — all that, O Mother, is but your sport.",
    32021: "When you desire contraction, O Girijaa, you are the groundless, nameless-formless substratum of speech and logic; when you desire expansion, the enumeration of your names and forms becomes easy.",
    32022: "The meritorious bow to you, O Devi, for enjoyment, and dwell a thousand ages in lotus-homes fanned by your brow — they revel forever in the wish-tree groves on the pleasure mountain of cintamani.",
    32023: "You alone are able to remove with compassion all the heat of worldly existence of the bound souls, O sovereign — just as only the collected rays of the sun (Vaikartani) can quench a fire by their own rain.",
    32024: "Power, body, the divine oversoul, inner self, knowledge, action, the senses, the lattice of seats, and will — is there anything, O Devi of moon-crested lord, that you are not?",
    32025: "Withdrawal has arisen in earth, stability in water, knowledge in fire, peace in wind, exceeding radiance — these indeed are the creative emanations that sustain the world; you are their source.",
    32026: "As long as the world does not accept your pair of lotus-feet, O refuge of the world, in its heart, so long will the hair-splitting arguments of the disputants be a tangled, twisted, winding delusion.",
    32027: "Some, making the mind-and-sense-complex sovereign, having journeyed beyond both the deva and the pitru paths, fixing it in meditation on the five causal levels of your being, O Parvati, pass the junctions of the seasons in their own seat.",
    32028: "Even of the goddess whose glory in her coarser forms — earth and the rest — cannot be declared by the Lord of speech himself, even she, O Mother, is said to have been praised.",
    32029: "Guru-teachers of the worlds meditate upon you in your dark form, dense-breasted, whose radiance dissolves the inauspiciousness — pouring forth an ambrosia shower in the six-path purification.",
    32030: "Some call you the supreme Vidya, some call you the sky, some bliss alone, some illusion — others call you the universe; we call you, O Guru, direct and boundless compassion.",
    32031: "Dark-blue as a blue-lotus petal, with thick lustrous tangled hair, girt with a slender waist beneath heavy full breasts — what more need be said? O universal Mother, be seen by us in your supreme form.",
    32032: "Colophon: Thus ends the fourth Ambaastava in the Panchastavi composed by Sri Kalidasa.",
}

DEVI_APARAJITA = {
    30405: "Salutations always to the Goddess, to the Great Goddess, to Shiva; salutations to Nature, to the auspicious one — those who are restrained bow down.",
    30406: "Salutations to the fierce one, to the eternal one, to Gauri, to the nourishing Dhata; salutations to the moonlit one, to her of moon-form, always to the blissful one.",
    30407: "Bowing to the auspicious one, to growth, to achievement — we offer repeated salutations; salutations to her of the southwest, to the Lakshmi of mountain-kings, to Sharvani.",
    30408: "Salutations always to Durga, the far-shore crosser, the essence, the all-doer, to the renowned one, to the dark one, to the smoke-hued one.",
    30409: "To the supremely gentle yet supremely fierce — bow, salutations again and again; salutation to the one established in the world, to the Devi who is all action.",
    30410: "Salutation, salutation, salutation again to that Devi abiding in all beings as the Vishnu-maya, known by the name Vishnu-illusion.",
    30411: "Salutation, salutation, salutation again to that Devi abiding in all beings, who is called Consciousness.",
    30412: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Intellect.",
    30413: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Sleep.",
    30414: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Hunger.",
    30415: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Shadow.",
    30416: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Power.",
    30417: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Thirst.",
    30418: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Patience.",
    30419: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Species or Caste.",
    30420: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Modesty.",
    30421: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Peace.",
    30422: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Faith.",
    30423: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Beauty and Radiance.",
    30424: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Lakshmi.",
    30425: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Activity and Livelihood.",
    30426: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Memory.",
    30427: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Compassion.",
    30428: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Contentment.",
    30429: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of the Mother.",
    30430: "Salutation, salutation, salutation again to that Devi abiding in all beings in the form of Illusion and Confusion.",
    30431: "Salutations again and again to the Devi who is the presiding ruler of the senses and of all beings, all-pervading and ever present in all creatures.",
    30432: "Salutation, salutation, salutation again to her who in the form of pure Consciousness pervades and dwells in this entire universe.",
}
